IHazDadJokes.MVC/IHazDadJokes.MVC/Controllers/HomeController.cs
using IHazDadJokes.API.Lib;
using IHazDadJokes.Infrastructure.HttpLib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IHazDadJokes.MVC.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
           return View();
        }        
    }
}

IHazDadJokes.MVC/IHazDadJokes.MVC/Controllers/JokesController.cs
using IHazDadJokes.API.Lib;
using IHazDadJokes.Infrastructure.HttpLib;
using System.Configuration;
using System.Threading.Tasks;
using System.Web.Mvc;
using DadJoke = IHazDadJokes.API.Lib.DadJoke;

namespace IHazDadJokes.MVC.Controllers
{
    public class JokesController : Controller
    {
        private readonly IDadJokesService _dadJokesService;
        private readonly IDadJokesServiceConfiguration _serviceConfig;

        public JokesController()
        {
            _serviceConfig = ConfigurationManager.GetSection("jokes") as DadJokesServiceConfiguration;
            _dadJokesService = new DadJokesService(new HttpClientWrapper(), _serviceConfig); 
        }

        [HttpGet]
        public async Task<ActionResult> RandomDadJoke()
        {
            return View(await GetRandomJoke());
        }        

        [HttpGet]
        public async Task<ActionResult> PartialRandomDadJoke()
        {
            return PartialView(await GetRandomJoke());
        }

        [HttpGet]
        public ActionResult SearchDadJoke()
        {
            ViewBag.Message = "Your Dad Jokes will be displayed here!";

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> PartialSearchDadJokes()
        {
            ViewBag.Message = "Here are the dad jokes with the word you searched!";
            ViewBag.IsResult = true;
            var searchTerm = Request["SearchTerm"];

            var viewModel = await _dadJokesService.GetDadJokesBySearchTerm(searchTerm);

            return PartialView(viewModel);
        }

        private async Task<DadJoke> GetRandomJoke()
        {
            return await _dadJokesService.GetRandomDadJoke();
        }
    }
}

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Dad Jokes!</h1>
    <p class="lead">Here you can find an awesome amount of great dad jokes from the great dad jokes 
    repository <a href="https://icanhazdadjokes.com">icanhazdadjokes.com</a>! Choose how you want to see your jokes below:</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Random Dad Jokes</h2>
        <p>
            Here you will be able to see a random dad joke every ten seconds!.
        </p>
        <p>@Html.ActionLink("Random Dad Jokes >>", "RandomDadJoke", "Jokes", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-6">
        <h2>Search Joke by Word</h2>
        <p>Here you can search your jokes for a theme of your choice! Just enter the word in the search bar and laugh your heart out!</p>
        <p>@Html.ActionLink("Search Dad Jokes >>", "SearchDadJoke", "Jokes", null, new { @class = "btn btn-default" })</p>
    </div>    
</div>

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Jokes/PartialRandomDadJoke.cshtml
@model IHazDadJokes.API.Lib.DadJoke

<div class="jumbotron">
    <div class="card">
        <h1>Random Dad Joke</h1>

        <blockquote class="blockquote mb-0">
            <p>@Html.DisplayFor(model => model.Joke)</p>
            <footer class="blockquote-footer">From https://icanhazdadjoke.com/</footer>
        </blockquote>
    </div>
</div>

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Jokes/PartialSearchDadJokes.cshtml
@model IHazDadJokes.API.Lib.DadJokesViewModel
@using System.Text.RegularExpressions

<table class="table">
    <tr>
        <th>
            @{var totalCount = Model.ShortDadJokes.Count() + Model.MediumDadJokes.Count() + Model.LongDadJokes.Count();}
            <h2>You searched for jokes with: <strong>@Model.SearchTerm</strong>. @totalCount jokes found!</h2>
        </th>
        <th></th>
    </tr>
</table>
@{
    var longJokes = Model.LongDadJokes;
    var mediumJokes = Model.MediumDadJokes;
    var shortJokes = Model.ShortDadJokes;
}
@if (shortJokes != null && shortJokes.Count() > 0)
{
    <p>Short jokes (less then 10 words): @Model.ShortDadJokes.Count() found</p>
    foreach (var joke in shortJokes)
    {
        <blockquote class="blockquote mb-0">
            @Html.Raw(PrintEmphasizedJoke(joke.Joke, Model.SearchTerm))
        </blockquote>
    }
}

@if (mediumJokes != null && mediumJokes.Count() > 0)
{
    <p>Medium jokes (less then 20 words):  @Model.MediumDadJokes.Count() found</p>
    foreach (var joke in mediumJokes)
    {
        <blockquote class="blockquote mb-0">
            @Html.Raw(PrintEmphasizedJoke(joke.Joke, Model.SearchTerm))
        </blockquote>
    }
}


@if (longJokes != null && longJokes.Count() > 0)
{
    <p>Long jokes (more then 20 words):  @Model.LongDadJokes.Count() found</p>
    foreach (var joke in longJokes)
    {
        <blockquote class="blockquote mb-0">
            @Html.Raw(PrintEmphasizedJoke(joke.Joke, Model.SearchTerm))
        </blockquote>
    }
}


@functions{
    public string PrintEmphasizedJoke(string joke, string searchTerm)
    {
        var emphasizedJoke = Regex.Replace(joke, searchTerm, $"<strong>{searchTerm}</strong>", RegexOptions.IgnoreCase);
        return emphasizedJoke;
    }
}

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Jokes/RandomDadJoke.cshtml
@model IHazDadJokes.API.Lib.DadJoke

@{
    ViewBag.Title = "DadJoke";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="dadJoke">
    @Html.Partial("PartialRandomDadJoke", Model)
</div>

<script type="text/javascript">
    function updateJoke() {
        $.ajax(
        {
                type: 'GET',
                url: '@Url.Action("PartialRandomDadJoke", "Jokes")',
                cache: false,
                async: true,
                success: function (data) {
                    $('#dadJoke').html(data);
                },
                error: function(data) {
                    console.log("Call failed:"+ data.status);
                }
            });
    }

    $(document).ready(function () {
        setInterval(updateJoke, 10000);
    });
</script>

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Jokes/SearchDadJoke.cshtml
@model IHazDadJokes.API.Lib.DadJokesViewModel

@{
    ViewBag.Title = "Search Dad Joke";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Dad Jokes</h2>

    <div class="form-horizontal">
        <h4>Search by dad jokes with this word:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SearchTerm, "Search Term",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SearchTerm, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SearchTerm, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">                
                <button type="button" class="btn btn-default" onclick="searchJokes($('#SearchTerm').val())">Search</button>
            </div>
        </div>
    </div>

    <div id="dadJokes">
        <p>@Html.Label((string)ViewBag.Message)</p>
        @{ 
            var isResult = (bool?)ViewBag.IsResult?.Value ?? false;
            if (isResult)
            {
                Html.Partial("PartialSearchDadJokes", Model);
            }
        }
    </div>

<script type="text/javascript">
    function searchJokes(searchTerm) {
        console.log(searchTerm);
        $.ajax(
            {
                type: 'POST',
                url: '@Url.Action("PartialSearchDadJokes", "Jokes")',
                cache: false,
                async: true,
                data: { "SearchTerm": searchTerm },
                success: function (data) {
                    $('#dadJokes').html(data);
                },
                error: function(data) {
                    console.log("Call failed:" + data.status);
                }
            });
    }
</script>

IHazDadJokes.MVC/IHazDadJokes.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Dad Jokes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Dad Jokes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Random Dad Joke", "RandomDadJoke", "Jokes")</li>
                    <li>@Html.ActionLink("Search Dad Joke", "SearchDadJoke", "Jokes")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - I Haz Dad Jokes Code Challenge - Lucas V.</p>
        </footer>
    </div>

   
</body>
</html>